# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startTest_2(object):
    def setupUi(self, startTest_2):
        startTest_2.setObjectName("startTest_2")
        startTest_2.resize(439, 354)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        startTest_2.setWindowIcon(icon)
        startTest_2.setStyleSheet("QDailog{\n"
"background-image: url(\'Images/logo01(Faded Croped).jpg\');\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: #ADD8E6;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(startTest_2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.testFile = QtWidgets.QLabel(startTest_2)
        self.testFile.setObjectName("testFile")
        self.horizontalLayout.addWidget(self.testFile)
        self.testSelect = QtWidgets.QPushButton(startTest_2)
        self.testSelect.setStyleSheet("background-color: #ADD8E6;")
        self.testSelect.setObjectName("testSelect")
        self.horizontalLayout.addWidget(self.testSelect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(startTest_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.noQ = QtWidgets.QLabel(startTest_2)
        self.noQ.setText("")
        self.noQ.setObjectName("noQ")
        self.horizontalLayout_2.addWidget(self.noQ)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(startTest_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.time = QtWidgets.QLabel(startTest_2)
        self.time.setText("")
        self.time.setObjectName("time")
        self.horizontalLayout_3.addWidget(self.time)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(startTest_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.percentage = QtWidgets.QLabel(startTest_2)
        self.percentage.setText("")
        self.percentage.setObjectName("percentage")
        self.horizontalLayout_4.addWidget(self.percentage)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.startTest = QtWidgets.QPushButton(startTest_2)
        self.startTest.setAutoFillBackground(False)
        self.startTest.setStyleSheet("background-color: #ADD8E6;")
        self.startTest.setObjectName("startTest")
        self.verticalLayout.addWidget(self.startTest)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(startTest_2)
        QtCore.QMetaObject.connectSlotsByName(startTest_2)

    def retranslateUi(self, startTest_2):
        _translate = QtCore.QCoreApplication.translate
        startTest_2.setWindowTitle(_translate("startTest_2", "Start Test"))
        self.testFile.setText(_translate("startTest_2", "open file"))
        self.testSelect.setText(_translate("startTest_2", "Select Test File "))
        self.label.setText(_translate("startTest_2", "Number of Question:"))
        self.label_2.setText(_translate("startTest_2", "Time Limit: "))
        self.label_3.setText(_translate("startTest_2", "Passing Percentage: "))
        self.startTest.setText(_translate("startTest_2", "Start Test "))
